# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

variable "zone" {}
variable "name" {}
variable "machine_type" { default = "f1-micro" }
variable "image" { default = "cos-cloud/cos-stable" }

variable "tw_username" { default = "anonymous" }
variable "tw_password" { default = "letmein" }
variable "domain" {}
variable "email" {}
variable "letsencrypt_data" { default = "/home/tiddlywiki/letsencrypt" }
variable "git_repository" {}
variable "git_username" {}
variable "git_ssh_key" {}

data "template_file" "environment" {
  template = "${file("${path.module}/tiddlywiki.env.tpl")}"
  vars {
    domain = "${var.domain}"
    email = "${var.email}"
    tw_username = "${var.tw_username}"
    tw_password = "${var.tw_password}"
    letsencrypt_data = "${var.letsencrypt_data}"
    git_repository = "${var.git_repository}"
    git_username = "${var.git_username}"
    git_ssh_key = "${file("${var.git_ssh_key}")}"
  }
}

resource "google_compute_instance" "tiddlywiki" {
  name         = "${var.name}"
  machine_type = "${var.machine_type}"
  zone         = "${var.zone}"

  boot_disk {
    initialize_params {
      image = "${var.image}"
    }
  }

  network_interface {
    network = "default"
    access_config {
      # Ephemeral IP
    }
  }

  scheduling {
    preemptible = false
    on_host_maintenance = "MIGRATE"
    automatic_restart = true
  }

  tags = ["trusted-ssh", "http-server", "https-server"]

  metadata {
    ssh-keys = "tiddlywiki:${file("~/.ssh/google_compute_engine.pub")}"
    user-data = "${file("cloud-config.yaml")}"
  }

  connection {
    type = "ssh"
    user = "tiddlywiki"
    script_path = "/home/tiddlywiki/terraform.sh"
    # An ssh-agent must be running if you want to use the default encypted
    # private key ~/.ssh/google_compute_engine generated by the gcloud tool.
    agent = true
    # private_key = "${file("~/.ssh/id_rsa")}"
  }

  provisioner "file" {
    content = "${data.template_file.environment.rendered}"
    destination = "/home/tiddlywiki/systemd/tiddlywiki.env"
  }
  provisioner "file" {
    source = "apache/"
    destination = "/home/tiddlywiki/docker/apache"
  }
  provisioner "file" {
    source = "automation/"
    destination = "/home/tiddlywiki/docker/automation"
  }
  provisioner "file" {
    source = "letsencrypt/"
    destination = "/home/tiddlywiki/docker/letsencrypt"
  }
  provisioner "file" {
    source = "tiddlywiki/"
    destination = "/home/tiddlywiki/docker/tiddlywiki"
  }
  provisioner "file" {
    source = "docker-compose.yaml"
    destination = "/home/tiddlywiki/docker/docker-compose.yaml"
  }
  provisioner "file" {
    source = "env-file"
    destination = "/home/tiddlywiki/docker/env-file"
  }
}
