DOMAIN="${domain}"
EMAIL="${email}"
TW_PASSWORD="${tw_password}"
TW_USERNAME="${tw_username}"
GIT_REPOSITORY="${git_repository}"
GIT_USERNAME="${git_username}"
GIT_PASSWORD="${git_password}"
LETSENCRYPT_DATA="${letsencrypt_data}"
