FROM httpd:2.4-alpine
ADD httpd.conf /usr/local/apache2/conf/httpd.conf
ADD tiddlywiki.conf /usr/local/apache2/conf/tiddlywiki.conf
ADD tiddlywiki.include /usr/local/apache2/conf/tiddlywiki.include
EXPOSE 80
EXPOSE 443
