#!/bin/sh

# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

set -ex

# Should we set DOMAIN to the external IP if it is not set?
#export DOMAIN="$(curl -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip")"

env

if ! grep -qE '^[^:]:.+' /usr/local/apache2/conf/tiddlywiki.passwd 2> /dev/null \
    && [ -n "$TW_USERNAME" ] && [ "$TW_PASSWORD" ] ; then
  htpasswd -c -b -B \
    /usr/local/apache2/conf/tiddlywiki.passwd \
    "$TW_USERNAME" \
    "$TW_PASSWORD"
fi

while [ ! -e /etc/letsencrypt/live/$DOMAIN/cert.pem ]
do
  echo "Waiting for SSL certificate to be generated ..."
  sleep 5
done

httpd -D FOREGROUND &
apache_pid=$!

ssl_certificate_changed () {
  [ -n "$(find "/etc/letsencrypt/live/$DOMAIN/" -mmin -30)" ]
}

nudge_apache () {
  if ssl_certificate_changed; then
    echo "SSL certification modification detected; sending SIGUSR1 to Apache PID $apache_pid ..."
    kill -SIGUSR1 $apache_pid
  fi
}

sleep 90
nudge_apache

while sleep 1800
do
  nudge_apache
done
