#!/bin/sh

# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

set -e

# Should we set DOMAIN to the external IP if it is not set?
#export DOMAIN="$(curl -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip")"

if [ -n "$DEBUG" ]; then
  set -x
  env
fi

# Create htpasswd file if necessary.
if ! grep -qE '^[^:]:.+' /usr/local/apache2/conf/tiddlywiki.passwd 2> /dev/null \
    && [ -n "$TW_USERNAME" ] && [ "$TW_PASSWORD" ] ; then
  htpasswd -c -b -B \
    /usr/local/apache2/conf/tiddlywiki.passwd \
    "$TW_USERNAME" \
    "$TW_PASSWORD"
fi

# Wait for SSL certificate to be created by letsencrypt container.
while [ ! -e /etc/letsencrypt/live/$DOMAIN/cert.pem ]
do
  echo "Waiting for SSL certificate ..."
  sleep 5
done

# Define if we should force a password even for read-only access.
if     [ -n "$TW_PRIVATE" ] \
  && ! [ "$TW_PRIVATE" = "0" ] \
  && ! [ "$TW_PRIVATE" = "false" ] ; then
  TW_PRIVATE="-DPrivate"
else
  TW_PRIVATE=""
fi

# Launch Apache as a background process.
httpd ${TW_PRIVATE} -D FOREGROUND &
apache_pid=$!

ssl_certificate_changed () {
  minutes="$1"
  if [ -z "$minutes" ]; then
    minutes=30
  fi
  if [ -n "$(find "/etc/letsencrypt/live/" -mmin -$minutes)" ] \
    && [ -e /etc/letsencrypt/live/$DOMAIN/cert.pem ]; then
    return 0
  fi
  return 1
}

nudge_apache () {
  minutes="$1"
  if ssl_certificate_changed "$minutes"; then
    echo "SSL certification modification detected; sending SIGUSR1 to Apache PID $apache_pid ..."
    kill -SIGUSR1 $apache_pid
  fi
}

# Perpetually check for any SSL certificate changes, and poke Apache to
# gracefully reload when necessary.
sleep 120
nudge_apache 2

while sleep 1800
do
  nudge_apache 30
done
