#!/bin/sh

# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

set -ex

env

if ! grep -qE '^[^:]:.+' /usr/local/apache2/conf/tiddlywiki.passwd 2> /dev/null \
    && [ -n "$TW_USERNAME" ] && [ "$TW_PASSWORD" ] ; then
  htpasswd -c -b -B \
    /usr/local/apache2/conf/tiddlywiki.passwd \
    "$TW_USERNAME" \
    "$TW_PASSWORD"
fi

while [ ! -e /etc/letsencrypt/live/$DOMAIN/cert.pem ]
do
  echo "Waiting for SSL certificate to be generated ..."
  sleep 5
done

exec httpd -D FOREGROUND
