#!/bin/sh

# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

# SSLCertificateFile /etc/letsencrypt/live/${DOMAIN}/cert.pem
# SSLCertificateKeyFile /etc/letsencrypt/live/${DOMAIN}/privkey.pem
# SSLCertificateChainFile /etc/letsencrypt/live/${DOMAIN}/fullchain.pem

set -e

# Should we set DOMAIN to the external IP if it is not set?
#export DOMAIN="$(curl -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip")"

if [ -n "$DEBUG" ]; then
  set -x
  env
fi

CONFPATH="/etc/letsencrypt"
LIVEPATH="$CONFPATH/live/$DOMAIN"
HTDOCS="/usr/local/apache2/htdocs"

if [ ! -d "$LIVEPATH" ]; then
  mkdir -p "$LIVEPATH"
fi

if [ ! -d "$HTDOCS/.well-known" ]; then
  mkdir -p "$HTDOCS/.well-known"
fi

cert_is_letsencrypt () {
  openssl x509 -in "$1" -text -noout 2>&1 \
    | grep -qEi "(letsencrypt\.org|Let.s Encrypt)"
}

domain_responds () {
  RC=1
  for try in 1 2 3 4 5
  do
    if [ -e "$HTDOCS/.well-known/tiddlywiki" ]; then
      MYSIG="$(cat "$HTDOCS/.well-known/tiddlywiki")"
    fi
    THEIRSIG="$(printf 'GET /.well-known/tiddlywiki\r\n\r\n' | nc "$1" 80)"
    if [ -n "$MYSIG" ] && [ -n "$THEIRSIG" ] && [ "$MYSIG" = "$THEIRSIG" ]; then
      RC=0
      break
    fi
    sleep 5
  done
  return $RC
}

while sleep 2 && [ -e "$CONFPATH/automation.startup" ]
do
  echo "Waiting for automation container to finish startup ..."
  sleep 3
done

# Generate a self-signed certificate until LetsEncrypt does it's thing.
if   [ ! -e "$LIVEPATH/cert.pem" ] \
  || [ ! -e "$LIVEPATH/privkey.pem" ] \
  || [ ! -e "$LIVEPATH/fullchain.pem" ]; then
  echo "Generating fallback self-signed certificate ..."
  openssl req \
    -subj "/CN=$DOMAIN/O=$DOMAIN/OU=$DOMAIN/L=Location/ST=State/C=GB" \
    -new -newkey rsa:4096 -days 1180 -nodes -x509 \
    -keyout "$LIVEPATH/privkey.pem" \
    -out "$LIVEPATH/cert.pem"
  cp "$LIVEPATH/cert.pem" "$LIVEPATH/fullchain.pem"
fi

# Generate initial LetsEncrypt certificate.
if ! cert_is_letsencrypt "$LIVEPATH/cert.pem" \
  && domain_responds "$DOMAIN" \
  && [ ! "$DOMAIN" = "localhost.localdomain" ] \
  && [ -n "$EMAIL" ] \
  && [ ! "$EMAIL" = "webmaster@localhost.localdomain" ]; then

  echo "Generating Let's Encrypt certificate ..."

  if [ -e "$LIVEPATH" ]; then
    rm -rf "$LIVEPATH"
  fi

  certbot certonly \
    --agree-tos \
    --non-interactive \
    --email "$EMAIL" \
    --config-dir "$CONFPATH" \
    --webroot \
    --webroot-path "$HTDOCS" \
    --domains "$DOMAIN"
fi

CERTPEM="$(find "$CONFPATH/live/$DOMAIN"* -name cert.pem)"
if [ ! -e "$LIVEPATH" ] && [ -n "$CERTPEM" ]; then
  echo "Creating symbolic link to Let's Encrypt live certificate directory ..."
  cd "$CONFPATH/live/"
  ln -sfn "$(basename "$(dirname "$CERTPEM")")" "$DOMAIN"
fi

# Display certificate information.
openssl x509 -in "$LIVEPATH/cert.pem" -text -noout

if ! cert_is_letsencrypt "$LIVEPATH/cert.pem"; then
  echo "Certificate $LIVEPATH/cert.pem is not from Let's Encrypt; gracefully exiting ..."
  exit 0
fi

# Launch cron daemon for LetsEncrypt to periodically refresh our certificate.
exec crond -l 6 -d 6 -f
