#!/bin/sh

# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

set -ex

TWBASE="/var/lib/tiddlywiki"
SYNCPATCH="/usr/local/src/syncer.patch"
SYNCSRC="/usr/local/lib/node_modules/tiddlywiki/core/modules/syncer.js"
SYNCDST="$TWBASE/mywiki/tiddlers/\$__core_modules_syncer.js"

cd "$TWBASE"

git_bytes () {
  du -s "$TWBASE/.git" 2>/dev/null | cut -d" " -f1
}

GITBYTES="$(git_bytes)"
STABLECNT=0
while [ -z "$GITBYTES" ] \
   || [ ! "$GITBYTES" = "$(git_bytes)" ] \
   || [ "$STABLECNT" -lt 4 ]
do
  echo "Waiting for Git repository to stabilize ..."
  sleep 5
  NEWGITBYTES="$(git_bytes)"
  if [ "$GITBYTES" = "$NEWGITBYTES" ]; then
    STABLECNT=$(( $STABLECNT + 1 ))
  fi
  GITBYTES="$NEWGITBYTES"
done

ls -l
if [ ! -d mywiki ]; then
  tiddlywiki mywiki --init server
fi

if [ ! -e "$SYNCDST" ]; then
  if [ ! -d mywiki/tiddlers ]; then
    mkdir -p mywiki/tiddlers
  fi
  cp "$SYNCSRC" "$SYNCDST"
  patch "$SYNCDST" "$SYNCPATCH"
fi

env

exec tiddlywiki mywiki --server "8080" \
  '$:/core/save/all' "text/plain" "text/html" \
  "$TW_USERNAME" "" "0.0.0.0"
