#!/bin/sh

# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

set -e

if [ -n "$DEBUG" ]; then
  set -x
fi

TWBASE="/var/lib/tiddlywiki"
SYNCPATCH="/usr/local/src/syncer.patch"
SYNCSRC="/usr/local/lib/node_modules/tiddlywiki/core/modules/syncer.js"
SYNCDST="$TWBASE/mywiki/tiddlers/\$__core_modules_syncer.js"

cd "$TWBASE"

while sleep 2 && [ -e mywiki/automation.startup ]
do
  echo "Waiting for automation container to finish startup ..."
  sleep 3
done

# Create an empty TiddlyWiki if necessary.
if [ ! -e mywiki/tiddlywiki.info ]; then
  cd "$TWBASE/mywiki"
  tiddlywiki . --init server
  cd "$TWBASE"
fi

# Patch the syncer.js module to not complain on errors.
if [ ! -e "$SYNCDST" ]; then
  if [ ! -d mywiki/tiddlers ]; then
    mkdir -p mywiki/tiddlers
  fi
  cp "$SYNCSRC" "$SYNCDST"
  patch "$SYNCDST" "$SYNCPATCH"
fi

if [ -n "$DEBUG" ]; then
  env
fi

# Start the NodeJS TiddlyWiki server on port 8080.
exec tiddlywiki mywiki --server "8080" \
  '$:/core/save/all' "text/plain" "text/html" \
  "$TW_USERNAME" "" "0.0.0.0"
