#!/bin/sh

# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

set -ex

TWBASE="/var/lib/tiddlywiki"
SYNCPATCH="/usr/local/src/syncer.patch"
SYNCSRC="/usr/local/lib/node_modules/tiddlywiki/core/modules/syncer.js"
SYNCDST="$TWBASE/mywiki/tiddlers/\$__core_modules_syncer.js"

cd "$TWBASE"

for try in 1 2 3 4 5
do
  if [ -d .git ]
  then
    break
  fi
  sleep 5
done

for try in 1 2 3 4 5
do
  if [ ! -d mywiki ] ; then
    if tiddlywiki mywiki --init server
    then
      break
    fi
    sleep 5
  fi
done

if [ ! -e "$SYNCDST" ]
then
  if [ ! -d mywiki/tiddlers ]
  then
    mkdir -p mywiki/tiddlers
  fi
  cp "$SYNCSRC" "$SYNCDST"
  patch "$SYNCDST" "$SYNCPATCH"
fi

if [ -z "$TW_PORT" ]
then
  TW_PORT="8080"
fi

if [ -z "$TW_HOST" ]
then
  TW_HOST="0.0.0.0"
fi

env

exec tiddlywiki mywiki --server "$TW_PORT" \
  "$TW_ROOTTIDDLER" "$TW_RENDERTYPE" "$TW_SERVETYPE" \
  "$TW_USERNAME" "$TW_PASSWORD" "$TW_HOST" "$TW_PATHPREFIX"
